// <auto-generated />
using System;
using MentalDepths.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentalDepths.Data.Migrations
{
    [DbContext(typeof(MentalDepthsDbContext))]
    [Migration("20230801124634_MadeDeleteBehaviourBetweenAplicantAndJobApplicationCascade")]
    partial class MadeDeleteBehaviourBetweenAplicantAndJobApplicationCascade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MentalDepths.Data.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Aplicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Specialisations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Aplicants");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Apointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasPassed")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Apointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("247a7f62-3cfb-4d10-94b5-b94bb5a32e57"),
                            Address = "Office",
                            ApplicationUserId = new Guid("010d67b6-964d-4248-9c9a-ad83215eaa4a"),
                            DateAndTime = new DateTime(2023, 8, 4, 15, 46, 33, 962, DateTimeKind.Local).AddTicks(4987),
                            HasPassed = false,
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4")
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f957a45a-d8df-439e-a50a-b1c0f87a69f2"),
                            AccessFailedCount = 0,
                            CityId = 2,
                            ConcurrencyStamp = "8bfa1fc0-3e4b-4058-bd4b-9a3478e6912f",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 962, DateTimeKind.Local).AddTicks(5503),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gogo_5a@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Georgiev",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOGO_5A@ABV.BG",
                            NormalizedUserName = "GEORGI_GEORGIEV",
                            PasswordHash = "AEURYT5Om/vAWq4WUwpcczVDGpG1kYUvNBlK8qjWEnjcs8I+7o6akHoUKN6N+md18A==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Lyubenov",
                            SecurityStamp = "661650d7-543b-4720-888e-6e28500f2ffb",
                            TwoFactorEnabled = false,
                            UserName = "Georgi_Georgiev"
                        },
                        new
                        {
                            Id = new Guid("010d67b6-964d-4248-9c9a-ad83215eaa4a"),
                            AccessFailedCount = 0,
                            CityId = 5,
                            ConcurrencyStamp = "2d4317e5-a283-4633-a825-42a7162cd09d",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 963, DateTimeKind.Local).AddTicks(5226),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ScaryHaxer@gmail.com",
                            EmailConfirmed = false,
                            FirstName = "Iliq",
                            IsDeleted = false,
                            LastName = "Steliov",
                            LockoutEnabled = false,
                            NormalizedEmail = "SCARYHAXER@GMAIL.COM",
                            NormalizedUserName = "ILIQ_STELIOV",
                            PasswordHash = "ALPqx1AmFDOKL1O9ESzzDe71UbWClaacPPjeN3wO6kur8IPBVF/kmHOr9c77hXVo6g==",
                            PhoneNumberConfirmed = false,
                            SecondName = "",
                            SecurityStamp = "3147428a-b3e3-40ac-99d2-7b268dc656fb",
                            TwoFactorEnabled = false,
                            UserName = "Iliq_Steliov"
                        },
                        new
                        {
                            Id = new Guid("308508b8-ce9e-470b-a122-8a77f576532e"),
                            AccessFailedCount = 0,
                            CityId = 27,
                            ConcurrencyStamp = "08ab34ef-d738-47db-95b6-212335c147fa",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 964, DateTimeKind.Local).AddTicks(4110),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ivan.Ivanov234@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.IVANOV234@GMAIL.COM",
                            NormalizedUserName = "IVAN_IVANOV",
                            PasswordHash = "ALm+jtOoX/JsrBWZvAp7psI91JSSU8xGRRkYkH4LJUzGreT/NI2L3lcVxgbMfEAUHQ==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Sirov",
                            SecurityStamp = "5d1dd9a5-e1df-4b2c-98e4-431ea6e44311",
                            TwoFactorEnabled = false,
                            UserName = "Ivan_Ivanov"
                        },
                        new
                        {
                            Id = new Guid("9953dce8-25f6-45f2-bf8c-816b92bb0e28"),
                            AccessFailedCount = 0,
                            CityId = 13,
                            ConcurrencyStamp = "6543684e-e891-4234-93e7-ea371bc02a63",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 965, DateTimeKind.Local).AddTicks(3012),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lilial_Izbora@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Lilial",
                            IsDeleted = false,
                            LastName = "Izbrannikov",
                            LockoutEnabled = false,
                            NormalizedEmail = "LILIAL_IZBORA@ABV.BG",
                            NormalizedUserName = "LILIAL_IZBRANNIKOV",
                            PasswordHash = "AMHCcObr7v/F3FN112wytaa8T1k/EG7leqnuYpnDc6G702rE6XaF+R8W2hy3vp+EAw==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Sabiev",
                            SecurityStamp = "99301622-23fe-4eb5-8194-c39379e4a39d",
                            TwoFactorEnabled = false,
                            UserName = "Lilial_Izbrannikov"
                        },
                        new
                        {
                            Id = new Guid("59a88704-3ae3-4554-ad39-81b1f0304069"),
                            AccessFailedCount = 0,
                            CityId = 22,
                            ConcurrencyStamp = "fbd1cc64-34c3-40d3-b3a9-7e4b66c7e524",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 966, DateTimeKind.Local).AddTicks(2137),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kolio_Zemev@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nikola",
                            IsDeleted = false,
                            LastName = "Zemelyarski",
                            LockoutEnabled = false,
                            NormalizedEmail = "KOLIO_ZEMEV@GMAIL.COM",
                            NormalizedUserName = "NIKOLA ZEMELYARSKI",
                            PasswordHash = "AIrakSWySwf7eRyGUT2nvJE6UWJF0NnSJDwuWylzwa96XQ741ElhnBvEXSywpY1UqA==",
                            PhoneNumberConfirmed = false,
                            SecondName = "",
                            SecurityStamp = "824c278f-9c74-41df-afd1-9ba15694d8e0",
                            TwoFactorEnabled = false,
                            UserName = "Nikola Zemelyarski"
                        },
                        new
                        {
                            Id = new Guid("a63c570e-8c25-449f-b89c-3df89bc0d17c"),
                            AccessFailedCount = 0,
                            CityId = 17,
                            ConcurrencyStamp = "cdbde529-3afc-4afd-8fcc-eb8e449b84f5",
                            CreatedOn = new DateTime(2023, 8, 1, 15, 46, 33, 967, DateTimeKind.Local).AddTicks(3846),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sasunionios_loliolios@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Dembe",
                            IsDeleted = false,
                            LastName = "Redglade",
                            LockoutEnabled = false,
                            NormalizedEmail = "SASUNIONIOS_LOLIOLIOS@ABV.BG",
                            NormalizedUserName = "DEMBE_REDGLADE",
                            PasswordHash = "ABn/L1QT2C81py4liYAwPaZ8YwDW0FQYIg+H+qTHWHv5GsYGY4Zx7zpQbvgs+P+PLw==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Nisantimetarottebe",
                            SecurityStamp = "aa563c90-7870-4fa5-b1e8-703f0d510a92",
                            TwoFactorEnabled = false,
                            UserName = "Dembe_Redglade"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gabrovo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Haskovo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kardzhali"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kyustendil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lovech"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pazardzhik"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pernik"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Razgrad"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Shumen"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Silistra"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Smolyan"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sofia City"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sofia (province)"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Targovishte"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Veliko Tarnovo"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Vidin"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Vratsa"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Yambol"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.JobApplicationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Certification")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ScannedDiploma")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("JobApplicationForms");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfSend")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationtId")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAOneTimePrescription")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialisations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Psychiatrist"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adolescent psycology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Prepubescent psycology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Post-war trauma"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Abnormal psychology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Biological psychology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cognitive psychology "
                        },
                        new
                        {
                            Id = 8,
                            Name = "Developmental psychology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Forensic psychology"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Counselling psychology"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Industrial-organizational psychology"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Forensic psychology"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Personality psychology"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Social psychology"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            Address = "AlenMak bl.14 vh.6",
                            Age = 23,
                            Description = "Talanted, young and abnormaly ambitious she will obliterate your expectations!",
                            ImageURL = "https://images.pexels.com/photos/3538028/pexels-photo-3538028.jpeg?cs=srgb&dl=pexels-jeys-tubianosa-3538028.jpg&fm=jpg",
                            UserId = new Guid("308508b8-ce9e-470b-a122-8a77f576532e")
                        },
                        new
                        {
                            Id = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            Address = "ul.\"Sergei Kirov\" vh.34",
                            Age = 56,
                            Description = "Talanted, not so young and rather slackish he will obliterate your expectations(in a bad way)!",
                            ImageURL = "https://images.pexels.com/photos/1936854/pexels-photo-1936854.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            UserId = new Guid("59a88704-3ae3-4554-ad39-81b1f0304069")
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.SpecialistSpecialisation", b =>
                {
                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpecialisationId")
                        .HasColumnType("int");

                    b.HasKey("SpecialistId", "SpecialisationId");

                    b.HasIndex("SpecialisationId");

                    b.ToTable("SpecialistsSpecialisations");

                    b.HasData(
                        new
                        {
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            SpecialisationId = 8
                        },
                        new
                        {
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            SpecialisationId = 4
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 13
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 6
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Admin", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Aplicant", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.JobApplicationForm", "JobApplication")
                        .WithOne("Aplicant")
                        .HasForeignKey("MentalDepths.Data.Models.Aplicant", "JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Apointment", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Apointments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Apointments")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.City", "City")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Conversations")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Message", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Note", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Conversation", "Conversation")
                        .WithOne("Note")
                        .HasForeignKey("MentalDepths.Data.Models.Note", "ConversationtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Prescription", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Prescriptions")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.SpecialistSpecialisation", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Specialisation", "Specialisation")
                        .WithMany("Specialists")
                        .HasForeignKey("SpecialisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Specialisations")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialisation");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Apointments");

                    b.Navigation("Conversations");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.City", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalDepths.Data.Models.JobApplicationForm", b =>
                {
                    b.Navigation("Aplicant")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialisation", b =>
                {
                    b.Navigation("Specialists");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.Navigation("Apointments");

                    b.Navigation("Conversations");

                    b.Navigation("Prescriptions");

                    b.Navigation("Specialisations");
                });
#pragma warning restore 612, 618
        }
    }
}
