// <auto-generated />
using System;
using MentalDepths.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentalDepths.Data.Migrations
{
    [DbContext(typeof(MentalDepthsDbContext))]
    partial class MentalDepthsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MentalDepths.Data.Models.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d947f5ab-75ae-4ebe-9f26-9af2671d77ac"),
                            UserId = new Guid("f957a45a-d8df-439e-a50a-b1c0f87a69f2"),
                            Username = "Big Boss"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.AdminJobApplicationMT", b =>
                {
                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminId", "JobApplicationId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("AdminJobApplicationMT");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Apointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Apointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("247a7f62-3cfb-4d10-94b5-b94bb5a32e57"),
                            Address = "Office",
                            ApplicationUserId = new Guid("010d67b6-964d-4248-9c9a-ad83215eaa4a"),
                            DateAndTime = new DateTime(2023, 7, 23, 15, 16, 9, 909, DateTimeKind.Local).AddTicks(3253),
                            IsConfirmed = false,
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4")
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f957a45a-d8df-439e-a50a-b1c0f87a69f2"),
                            AccessFailedCount = 0,
                            CityId = 2,
                            ConcurrencyStamp = "54f3c275-f6cc-4bb6-acff-4cb790addec6",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 909, DateTimeKind.Local).AddTicks(3388),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gogo_5a@abv.bg",
                            EmailConfirmed = true,
                            FirstName = "Georgi",
                            IsDeleted = false,
                            LastName = "Georgiev",
                            LockoutEnabled = false,
                            NormalizedEmail = "GOGO_5A@ABV.BG",
                            NormalizedUserName = "GEORGI GEORGIEV",
                            PasswordHash = "AA+UPL4FAVwX9u5RnJF6MqMBtOwNbEz/WVWBoH3iz8tz8U7LWeE0G1xJ7foKowFKuA==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Lyubenov",
                            SecurityStamp = "a29424cb-a2ca-463c-9f4c-f4f89c0ed74e",
                            TwoFactorEnabled = false,
                            UserName = "Georgi Georgiev"
                        },
                        new
                        {
                            Id = new Guid("010d67b6-964d-4248-9c9a-ad83215eaa4a"),
                            AccessFailedCount = 0,
                            CityId = 5,
                            ConcurrencyStamp = "f36b4bca-a88a-4b96-a2f9-f8f132833289",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 909, DateTimeKind.Local).AddTicks(8088),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ScaryHaxer@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "Iliq",
                            IsDeleted = false,
                            LastName = "Steliov",
                            LockoutEnabled = false,
                            NormalizedEmail = "SCARYHAXER@YAHOO.COM",
                            NormalizedUserName = "ILIQ STELIOV",
                            PasswordHash = "AMSG2VM9iWWt2Z7uwmhiE/HrXeP7Xxf5Jrb0zy/Lieuv3lEStv8SH5pbgrdV9ODvQg==",
                            PhoneNumberConfirmed = false,
                            SecondName = "",
                            SecurityStamp = "c5b06056-1248-4eb7-8d7f-33fdc14fd74b",
                            TwoFactorEnabled = false,
                            UserName = "Iliq Steliov"
                        },
                        new
                        {
                            Id = new Guid("308508b8-ce9e-470b-a122-8a77f576532e"),
                            AccessFailedCount = 0,
                            CityId = 27,
                            ConcurrencyStamp = "92db1c51-5510-42a8-9123-55984274bba8",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 910, DateTimeKind.Local).AddTicks(2582),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ivan.Ivanov234@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ivan",
                            IsDeleted = false,
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "IVAN.IVANOV234@GMAIL.COM",
                            NormalizedUserName = "IVAN IVANOV",
                            PasswordHash = "AKE2y6DfvfG6NZe5MZuZqxKlgWVCuz4tD5+15gBPBvM+ckCBqxPCLRah6txlX7yplg==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Sirov",
                            SecurityStamp = "5f529cbf-1b42-4250-bf3c-8f214cab6d42",
                            TwoFactorEnabled = false,
                            UserName = "Ivan Ivanov"
                        },
                        new
                        {
                            Id = new Guid("9953dce8-25f6-45f2-bf8c-816b92bb0e28"),
                            AccessFailedCount = 0,
                            CityId = 13,
                            ConcurrencyStamp = "3ef91059-e4a3-47bf-8067-fd76c742e042",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 910, DateTimeKind.Local).AddTicks(7146),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lilial_Izbora@abv.bg",
                            EmailConfirmed = false,
                            FirstName = "Lilial",
                            IsDeleted = false,
                            LastName = "Izbrannikov",
                            LockoutEnabled = false,
                            NormalizedEmail = "LILIAL_IZBORA@ABV.BG",
                            NormalizedUserName = "LILIAL IZBRANNIKOV",
                            PasswordHash = "ADADshnv3xCJfY09C2za2xvKCh59Pf995AoWtLRVrr5n+XhSaUxBXSzrK8WDDyDM/A==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Sabiev",
                            SecurityStamp = "032f43ee-2241-4539-8272-6c66b99e026d",
                            TwoFactorEnabled = false,
                            UserName = "Lilial Izbrannikov"
                        },
                        new
                        {
                            Id = new Guid("59a88704-3ae3-4554-ad39-81b1f0304069"),
                            AccessFailedCount = 0,
                            CityId = 22,
                            ConcurrencyStamp = "5622a30b-fdc9-405b-a6b9-6ea197fda277",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 911, DateTimeKind.Local).AddTicks(1736),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Kolio_Zemev@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nikola",
                            IsDeleted = false,
                            LastName = "Zemelyarski",
                            LockoutEnabled = false,
                            NormalizedEmail = "KOLIO_ZEMEV@GMAIL.COM",
                            NormalizedUserName = "NIKOLA ZEMELYARSKI",
                            PasswordHash = "ALg6FhwmimXhe350cw6k05JtxTvGsKD9h0O+yd0vI7VITSXgyr7GqadXeiOSym8DZA==",
                            PhoneNumberConfirmed = false,
                            SecondName = "",
                            SecurityStamp = "57a9b75b-ecce-477e-a09e-614e96d3f621",
                            TwoFactorEnabled = false,
                            UserName = "Nikola Zemelyarski"
                        },
                        new
                        {
                            Id = new Guid("a63c570e-8c25-449f-b89c-3df89bc0d17c"),
                            AccessFailedCount = 0,
                            CityId = 17,
                            ConcurrencyStamp = "51ce3358-8cb8-40c1-832b-99778177f133",
                            CreatedOn = new DateTime(2023, 7, 20, 15, 16, 9, 911, DateTimeKind.Local).AddTicks(6196),
                            DeletedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "DembeRed@alo.net",
                            EmailConfirmed = false,
                            FirstName = "Dembe",
                            IsDeleted = false,
                            LastName = "Redglade",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEMBERED@ALO.NET",
                            NormalizedUserName = "DEMBE REDGLADE",
                            PasswordHash = "AMOJZMv05rnjJPeeAlt1QMf3Bq3jjbkGCuinM2AcdKlJlovlrBqs/Jnp8wPKUolJSg==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Nisantimetarottebe",
                            SecurityStamp = "6e5dbc0d-56f3-4dd0-a9fb-acd411afe882",
                            TwoFactorEnabled = false,
                            UserName = "Dembe Redglade"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ""
                        },
                        new
                        {
                            Id = 2,
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gabrovo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Haskovo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kardzhali"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kyustendil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lovech"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pazardzhik"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pernik"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Razgrad"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Shumen"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Silistra"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Smolyan"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Sofia City"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sofia (province)"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Targovishte"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Veliko Tarnovo"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Vidin"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Vratsa"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Yambol"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.JobApplicationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("CV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Certification")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ScannedDiploma")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpecialistId")
                        .IsUnique();

                    b.ToTable("JobApplicationForms");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfSend")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeOfUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationtId")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAOneTimePrescription")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("SpecialistId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Specialisations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Psychiatrist"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adolescent psycology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Prepubescent psycology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Post-war trauma"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Abnormal psychology"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Biological psychology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cognitive psychology "
                        },
                        new
                        {
                            Id = 8,
                            Name = "Developmental psychology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Forensic psychology"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Counselling psychology"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Industrial-organizational psychology"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Forensic psychology"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Personality psychology"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Social psychology"
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            Address = "AlenMak bl.14 vh.6",
                            Age = 23,
                            Description = "Talanted, young and abnormaly ambitious she will obliterate your expectations!",
                            ImageURL = "https://images.pexels.com/photos/3538028/pexels-photo-3538028.jpeg?cs=srgb&dl=pexels-jeys-tubianosa-3538028.jpg&fm=jpg",
                            JobApplicationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserId = new Guid("308508b8-ce9e-470b-a122-8a77f576532e")
                        },
                        new
                        {
                            Id = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            Address = "ul.\"Sergei Kirov\" vh.34",
                            Age = 56,
                            Description = "Talanted, young and abnormaly ambitious he will obliterate your expectations!",
                            ImageURL = "https://images.pexels.com/photos/1936854/pexels-photo-1936854.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
                            JobApplicationId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserId = new Guid("59a88704-3ae3-4554-ad39-81b1f0304069")
                        });
                });

            modelBuilder.Entity("MentalDepths.Data.Models.SpecialistSpecialisation", b =>
                {
                    b.Property<Guid>("SpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SpecialisationId")
                        .HasColumnType("int");

                    b.HasKey("SpecialistId", "SpecialisationId");

                    b.HasIndex("SpecialisationId");

                    b.ToTable("SpecialistsSpecialisations");

                    b.HasData(
                        new
                        {
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            SpecialisationId = 8
                        },
                        new
                        {
                            SpecialistId = new Guid("33713803-661e-4fad-a041-cf526fbc83e4"),
                            SpecialisationId = 4
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 13
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 6
                        },
                        new
                        {
                            SpecialistId = new Guid("550184af-0284-4a1c-bc3e-223cb9198e62"),
                            SpecialisationId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Admin", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.AdminJobApplicationMT", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Admin", "Admin")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.JobApplicationForm", "JobApplicationForm")
                        .WithMany("Admins")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("JobApplicationForm");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Apointment", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Apointments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Apointments")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.City", "City")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Conversations")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.JobApplicationForm", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithOne("JobApplication")
                        .HasForeignKey("MentalDepths.Data.Models.JobApplicationForm", "SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Message", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Note", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Conversation", "Conversation")
                        .WithOne("Note")
                        .HasForeignKey("MentalDepths.Data.Models.Note", "ConversationtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Prescription", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Prescriptions")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.SpecialistSpecialisation", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.Specialisation", "Specialisation")
                        .WithMany("Specialists")
                        .HasForeignKey("SpecialisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.Specialist", "Specialist")
                        .WithMany("Specialisations")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialisation");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MentalDepths.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Admin", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Apointments");

                    b.Navigation("Conversations");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.City", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("MentalDepths.Data.Models.JobApplicationForm", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialisation", b =>
                {
                    b.Navigation("Specialists");
                });

            modelBuilder.Entity("MentalDepths.Data.Models.Specialist", b =>
                {
                    b.Navigation("Apointments");

                    b.Navigation("Conversations");

                    b.Navigation("JobApplication")
                        .IsRequired();

                    b.Navigation("Prescriptions");

                    b.Navigation("Specialisations");
                });
#pragma warning restore 612, 618
        }
    }
}
